[package]
name = "wingman"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1"
env_logger = "0.11"
log = "0.4"
pollster = "0.4"
winit = "0.30"
wgpu = "28"
glyphon = "0.10"
bytemuck = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
wgpu = { version = "28", features = ["webgl"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Window", "Element"] }

[[bin]]
name = "desktop"
path = "src/main.rs"
